# language compare using gRPC configuration

# servers providing function execution
servers:
  # python gRPC test server
  py_server:
    type: py
    port: 50051

  # typescript gRPC test server
  # port is currently hard coded to 50052 in cpp source code
  # don't change the port number below
  ts_server:
    type: typescript
    port: 50052

# available test runners to compare function results from multiple languages
runners:
  # compare language implementations of xor cipher
  test_xor_cipher:
    cmd: python3 -m pytest xor_cipher_test.py --hypothesis-show-statistics --disable-warnings -v

  # compare language implementations of sqrt
  sqrt_test:
    cmd: python3 -m pytest sqrt_test.py --hypothesis-show-statistics --disable-warnings -v


# list of runs to execute
runs:
  - test_xor_cipher
  - sqrt_test

